spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: task-service
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/tasks/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

